#:import menu menu
MainWidget:



<MainWidget>:
    canvas.before:
        Rectangle:
            size:self.size
            source: 'Bg.jpg'
    menu_widget:menu_widget
    ppx: self.width/2
    ppy: self.height*0.75
    MenuWidget:
        id: menu_widget
    Label:
        text:root.score_txt
        font_size:dp(20)
        size_hint:.2, .2
        pos_hint: {'x':0.02, 'top':0.961}
        color: 0.5, 0.5, 1, 1
        bgcolor: 0.5, 0, 0, 2